### ISSUE TITLE
setuptools doesn't like version number 0.1.1a 

### ISSUE THREAD

**Issue by dkg** [rshk/python-libxdo#11]
when i use setuptools on debian testing (18.8-1), it complains about the python-libxdo version number 0.1.1a:

```
  /usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1.1a' to '0.1.1a0'
```

@rshk wrote:

> I guess rules on package version parsing were changed a bit.. the trailing
> "a" means "alpha", and once it was perfectly acceptable to omit the extra
> digit.. probably best thing would be to just normalize it to "a0" in the
> development version, then drop the a* part for the stable (tagged) releases.

**Comment by rshk** [comment]
Fixed in af2cfdfb55c87ff8cf8c7974bb81f127103bde1b
