### ISSUE TITLE
bump version and publish to pypi

### ISSUE THREAD

**Issue by mzizzi** [rshk/python-libxdo#14]
This project has received several bugfixes since the last release.  Perhaps we could bump the version to `0.1.1a1` and publish to pypi for those projects that depend on python-libxdo.  It would be nice for those using pip to install this package to receive a "more bug free" package.

**Comment by rshk** [comment]
Actually, we're working towards a 1.0 version, to be renamed as ``python-xdo``.
Once that one is released, there will be a "last" release of ``python-libxdo``, only containing a dependency on ``python-xdo``, as to avoid breaking 3rd party dependencies..

**Comment by rshk** [comment]
Enjoy https://pypi.python.org/pypi/python-libxdo/0.1.2a0 in the meanwhile :wink:
